Commenter = Ctrl + K + C  
Décommenter = Ctrl + K + U  
Indentation = Ctrl + K + D
Complétion = Alt + Entrer
Saut a la ligne = \n
Tabulation + tiret = \t
Console.WriteLine(); = c + w + tab + tab
Boucle for = f + o + tab + tab
Demarrer l'application = F5
Mode plein ecran = Maj + Alt + Entrée
Dupliquer la ligne = Ctrl + D